# -*- coding: utf-8 -*-
"""EmotionRecognition_Creatica.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SCkdL7cKtiShGX_NCXq5ofYDkM9wGC8L
"""

!pip install deepface

from deepface import DeepFace
import cv2
import matplotlib.pyplot as plt

img1_path = "/1.jpg"
img2_path = "/2.jpg"
img3_path = "/3.jpg"
img4_path = "/4.jpg"
img5_path = "/5.jpg"
img1 = cv2.imread(img1_path)
img2 = cv2.imread(img2_path)
img3 = cv2.imread(img3_path)
img4 = cv2.imread(img4_path)
img5 = cv2.imread(img5_path)
plt.imshow(img1[:,:,::-1])
plt.show()
plt.imshow(img2[:,:,::-1])
plt.show()
plt.imshow(img3[:,:,::-1])
plt.show()
plt.imshow(img4[:,:,::-1])
plt.show()
plt.imshow(img5[:,:,::-1])
plt.show()

person1 = DeepFace.analyze(img1_path)['emotion']
# person1
person2 = DeepFace.analyze(img2_path)['emotion']
# person2
person3 = DeepFace.analyze(img3_path)['emotion']
# person3
person4 = DeepFace.analyze(img4_path)['emotion']
# person4
person5 = DeepFace.analyze(img5_path)['emotion']
person1, person2, person3, person4, person5

import pandas as pd
df = pd.DataFrame([person1, person2, person3, person4, person5])
confused_averages = dict(df.mean())
print(confused_averages)

img6_path = "/deepa1.jpg"
img7_path = "/deepa2.jpg"
img6 = cv2.imread(img6_path)
img7 = cv2.imread(img7_path)
plt.imshow(img6[:,:,::-1])
plt.show()
plt.imshow(img7[:,:,::-1])
plt.show()
understanding_deepa = DeepFace.analyze(img6_path)['emotion']
confused_deepa = DeepFace.analyze(img7_path)['emotion']
understanding_deepa, confused_deepa

# confused_averages, understanding_deepa, confused_deepa
confused_diff = {x: confused_averages[x] - confused_deepa[x] for x in confused_averages if x in confused_deepa}
understanding_diff = {x: confused_averages[x] - understanding_deepa[x] for x in confused_averages if x in understanding_deepa}
confused_diff, understanding_diff

